all: hello status pt2pt collective

hello:
	CC hello.c -o hello

status:
	CC status.c -o status

pt2pt:
	CC pt2pt.c -o pt2pt

collective:
	CC collective.c -o collective

clean:
	rm hello status pt2pt collective
