all: hello status pt2pt collective

hello: hello.c
	CC hello.c -o hello

status: status.c
	CC status.c -o status

pt2pt: pt2pt.c
	CC pt2pt.c -o pt2pt

collective: collective.c
	CC collective.c -o collective

clean:
	rm hello status pt2pt collective
