all: writeAll readAll readOneRow writeRowsSer

writeAll: writeAll.cpp
	CC writeAll.cpp -o writeAll

readAll: readAll.cpp
	CC readAll.cpp -o readAll

readOneRow: readOneRow.cpp
	CC readOneRow.cpp -o readOneRow

writeRowsSer: writeRowsSer.cpp
	CC writeRowsSer.cpp -o writeRowsSer
